#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 11 20:59:10 MSK 2023
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim my_func_tb_behav -key {Behavioral:sim_1:Functional:my_func_tb} -tclbatch my_func_tb.tcl -view /home/leonid/Desktop/university/year3/DigitalCircuitry/lab3/my_func_tb_behav.wcfg -log simulate.log"
xsim my_func_tb_behav -key {Behavioral:sim_1:Functional:my_func_tb} -tclbatch my_func_tb.tcl -view /home/leonid/Desktop/university/year3/DigitalCircuitry/lab3/my_func_tb_behav.wcfg -log simulate.log

